"""
En esta actividad trabajarás con un archivo de texto llamado "Fragmento El Principito.txt" en el que puedes encontrar una parte de la novela "El principito", misma que cargarás en memoria para buscar información relevante para el control de una biblioteca.

Es importante que el archivo se encuentre en el mismo directorio que tu script, de otra manera tendrás que colocar la ruta completa para poder leerlo.

Después de cargar la información, deberás realizar la codificación de las siguientes tareas:

1. Una función para obtener la lista de palabras del archivo.
2. Una función que reciba la lista de palabras y obtenga la cantidad de palabras aproximadas que tiene el archivo.
3. Una función que reciba la lista de palabras y obtenga el promedio de letras que tienen las palabras.
4. Una función que reciba la lista de palabras y regrese una tupla con dos valores: el primero representa la cantidad de palabras que comienzan con una vocal y el segundo representa la cantidad de palabras que comienzan con una consonante.
5. Una función que reciba la lista de palabras y regrese un diccionario donde las llaves son las letras del abecedario y cada elemento una lista de las palabras que comienzan con dicha letra. 
6. Una función que reciba el texto en formato cadena y regrese el conteo de los signos de puntuación que se utilizaron. 
"""